import { db } from "@/lib/db";

export const EXERCISE_CATALOG = [
  { name: "Agachamento livre", muscleGroup: "Pernas", equipment: "Peso corporal ou barra", instructions: "Mantenha os pés firmes, controle a descida e use uma amplitude confortável." },
  { name: "Avanço alternado", muscleGroup: "Pernas", equipment: "Peso corporal ou halteres", instructions: "Dê um passo estável e mantenha o joelho alinhado ao pé." },
  { name: "Elevação pélvica", muscleGroup: "Glúteos", equipment: "Peso corporal ou barra", instructions: "Eleve o quadril sem hiperestender a região lombar." },
  { name: "Flexão de braços", muscleGroup: "Peito", equipment: "Peso corporal", instructions: "Mantenha tronco e quadril alinhados; use apoio elevado se necessário." },
  { name: "Supino reto", muscleGroup: "Peito", equipment: "Barra ou halteres", instructions: "Use pegada estável e movimento controlado, sem rebater a carga." },
  { name: "Supino inclinado com halteres", muscleGroup: "Peito", equipment: "Halteres", instructions: "Ajuste o banco, mantenha os pés apoiados e controle a descida dos halteres." },
  { name: "Supino máquina", muscleGroup: "Peito", equipment: "Máquinas", instructions: "Ajuste o banco para alinhar as mãos ao peito e empurre sem travar os cotovelos." },
  { name: "Supino inclinado na máquina", muscleGroup: "Peito", equipment: "Máquinas", instructions: "Ajuste o assento para que as alças fiquem na linha superior do peito e empurre com controle." },
  { name: "Supino declinado com barra", muscleGroup: "Peito", equipment: "Barra", instructions: "Prenda as pernas no banco, mantenha as escápulas apoiadas e controle a barra até a parte inferior do peito." },
  { name: "Chest press convergente", muscleGroup: "Peito", equipment: "Máquinas", instructions: "Ajuste o assento, mantenha as costas apoiadas e aproxime as alças sem perder o controle." },
  { name: "Peck deck", muscleGroup: "Peito", equipment: "Máquinas", instructions: "Ajuste o assento, mantenha o peito apoiado e feche os braços sem usar impulso." },
  { name: "Crucifixo máquina", muscleGroup: "Peito", equipment: "Máquinas", instructions: "Ajuste o assento para alinhar os braços ao peito e feche a máquina mantendo leve flexão dos cotovelos." },
  { name: "Crossover no cabo", muscleGroup: "Peito", equipment: "Cabos", instructions: "Mantenha o tronco estável e aproxime as mãos à frente do corpo com os cotovelos levemente flexionados." },
  { name: "Crucifixo no cabo", muscleGroup: "Peito", equipment: "Cabos", instructions: "Abra e feche os braços com controle, mantendo a posição dos cotovelos durante o movimento." },
  { name: "Remada sentada", muscleGroup: "Costas", equipment: "Cabo", instructions: "Puxe em direção ao tronco mantendo os ombros longe das orelhas." },
  { name: "Puxada frontal", muscleGroup: "Costas", equipment: "Cabo", instructions: "Puxe a barra à frente do corpo sem usar impulso." },
  { name: "Puxada alta", muscleGroup: "Costas", equipment: "Cabos", instructions: "Ajuste o apoio das pernas e puxe a barra em direção à parte alta do peito." },
  { name: "Remada baixa", muscleGroup: "Costas", equipment: "Cabos", instructions: "Mantenha o tronco estável e puxe o pegador em direção ao abdômen." },
  { name: "Remada máquina", muscleGroup: "Costas", equipment: "Máquinas", instructions: "Ajuste o apoio do peito e conduza os cotovelos para trás sem elevar os ombros." },
  { name: "Barra fixa assistida", muscleGroup: "Costas", equipment: "Máquinas", instructions: "Ajuste a assistência, estabilize o corpo e puxe até os cotovelos se aproximarem do tronco." },
  { name: "Puxada aberta na frente", muscleGroup: "Costas", equipment: "Cabos", instructions: "Use pegada aberta e puxe a barra em direção à parte alta do peito sem balançar o tronco." },
  { name: "Puxada neutra", muscleGroup: "Costas", equipment: "Cabos", instructions: "Use o pegador neutro e conduza os cotovelos para baixo mantendo o peito elevado." },
  { name: "Puxada supinada", muscleGroup: "Costas", equipment: "Cabos", instructions: "Segure a barra com as palmas voltadas para você e puxe mantendo o tronco estável." },
  { name: "Remada cavalinho", muscleGroup: "Costas", equipment: "Barra ou máquinas", instructions: "Mantenha a coluna neutra e puxe o pegador em direção ao tronco sem usar impulso." },
  { name: "Remada articulada", muscleGroup: "Costas", equipment: "Máquinas", instructions: "Ajuste o banco e conduza os cotovelos para trás de forma controlada." },
  { name: "Remada unilateral na máquina", muscleGroup: "Costas", equipment: "Máquinas", instructions: "Mantenha o peito apoiado e puxe uma alça por vez sem girar o tronco." },
  { name: "Remada baixa com triângulo", muscleGroup: "Costas", equipment: "Cabos", instructions: "Puxe o triângulo em direção ao abdômen mantendo a coluna neutra e os ombros baixos." },
  { name: "Pulldown com braços estendidos", muscleGroup: "Costas", equipment: "Cabos", instructions: "Mantenha os braços quase estendidos e leve a barra até as coxas sem balançar o corpo." },
  { name: "Desenvolvimento de ombros", muscleGroup: "Ombros", equipment: "Halteres", instructions: "Controle a carga e evite compensar com a lombar." },
  { name: "Desenvolvimento na máquina", muscleGroup: "Ombros", equipment: "Máquinas", instructions: "Ajuste o assento, mantenha as costas apoiadas e empurre dentro de uma amplitude confortável." },
  { name: "Elevação lateral", muscleGroup: "Ombros", equipment: "Halteres", instructions: "Eleve os braços com controle até uma amplitude confortável." },
  { name: "Elevação lateral no cabo", muscleGroup: "Ombros", equipment: "Cabos", instructions: "Mantenha o tronco estável e eleve o braço lateralmente sem impulso." },
  { name: "Elevação lateral na máquina", muscleGroup: "Ombros", equipment: "Máquinas", instructions: "Ajuste o assento, apoie os braços e eleve até uma amplitude confortável." },
  { name: "Elevação frontal", muscleGroup: "Ombros", equipment: "Halteres", instructions: "Eleve os halteres à frente com controle, sem balançar o tronco." },
  { name: "Desenvolvimento Arnold", muscleGroup: "Ombros", equipment: "Halteres", instructions: "Gire os braços durante a subida mantendo o tronco apoiado e o movimento controlado." },
  { name: "Crucifixo inverso na máquina", muscleGroup: "Ombros", equipment: "Máquinas", instructions: "Ajuste o assento de frente para o apoio e abra os braços sem elevar os ombros." },
  { name: "Face pull", muscleGroup: "Ombros", equipment: "Cabos", instructions: "Puxe a corda em direção ao rosto abrindo os cotovelos e mantendo os ombros baixos." },
  { name: "Remada alta no cabo", muscleGroup: "Ombros", equipment: "Cabos", instructions: "Puxe a barra até a altura confortável mantendo-a próxima ao corpo." },
  { name: "Encolhimento na máquina", muscleGroup: "Ombros", equipment: "Máquinas", instructions: "Eleve os ombros verticalmente sem girá-los e retorne de forma controlada." },
  { name: "Rosca direta", muscleGroup: "Bíceps", equipment: "Barra ou halteres", instructions: "Mantenha os cotovelos estáveis e evite balanço do tronco." },
  { name: "Rosca Scott", muscleGroup: "Bíceps", equipment: "Máquinas", instructions: "Ajuste o banco, apoie os braços e movimente a carga sem retirar os cotovelos do apoio." },
  { name: "Rosca máquina", muscleGroup: "Bíceps", equipment: "Máquinas", instructions: "Ajuste o banco e mantenha os braços apoiados enquanto flexiona os cotovelos." },
  { name: "Rosca no cabo", muscleGroup: "Bíceps", equipment: "Cabos", instructions: "Mantenha os cotovelos junto ao corpo e flexione-os sem deslocar os ombros." },
  { name: "Rosca concentrada", muscleGroup: "Bíceps", equipment: "Halteres", instructions: "Apoie o braço na parte interna da coxa e flexione o cotovelo sem mover o tronco." },
  { name: "Rosca inclinada com halteres", muscleGroup: "Bíceps", equipment: "Halteres", instructions: "Apoie as costas no banco inclinado e flexione os cotovelos mantendo os braços para baixo." },
  { name: "Rosca Scott unilateral", muscleGroup: "Bíceps", equipment: "Máquinas", instructions: "Apoie completamente o braço e execute um lado por vez com movimento controlado." },
  { name: "Rosca martelo no cabo", muscleGroup: "Bíceps", equipment: "Cabos", instructions: "Use a corda com pegada neutra e mantenha os cotovelos estáveis." },
  { name: "Rosca spider", muscleGroup: "Bíceps", equipment: "Halteres", instructions: "Apoie o peito no banco inclinado e flexione os cotovelos sem projetar os ombros." },
  { name: "Tríceps no cabo", muscleGroup: "Tríceps", equipment: "Cabo", instructions: "Estenda os cotovelos sem movimentar excessivamente os ombros." },
  { name: "Tríceps corda", muscleGroup: "Tríceps", equipment: "Cabos", instructions: "Mantenha os cotovelos junto ao corpo e afaste as pontas da corda ao final da extensão." },
  { name: "Tríceps máquina", muscleGroup: "Tríceps", equipment: "Máquinas", instructions: "Ajuste o assento, mantenha os cotovelos alinhados ao eixo e estenda os braços com controle." },
  { name: "Tríceps pulley com barra", muscleGroup: "Tríceps", equipment: "Cabos", instructions: "Mantenha os cotovelos junto ao corpo e empurre a barra para baixo sem movimentar os ombros." },
  { name: "Tríceps acima da cabeça no cabo", muscleGroup: "Tríceps", equipment: "Cabos", instructions: "Posicione a corda acima e atrás da cabeça e estenda os cotovelos mantendo-os apontados para a frente." },
  { name: "Tríceps testa no cabo", muscleGroup: "Tríceps", equipment: "Cabos", instructions: "Mantenha os braços estáveis e estenda os cotovelos controlando o retorno da carga." },
  { name: "Tríceps unilateral no cabo", muscleGroup: "Tríceps", equipment: "Cabos", instructions: "Execute um braço por vez mantendo o cotovelo junto ao corpo." },
  { name: "Tríceps coice com halter", muscleGroup: "Tríceps", equipment: "Halteres", instructions: "Apoie o tronco, mantenha o braço paralelo ao corpo e estenda somente o cotovelo." },
  { name: "Supino fechado", muscleGroup: "Tríceps", equipment: "Barra", instructions: "Use uma pegada confortável mais fechada e mantenha os cotovelos próximos ao corpo." },
  { name: "Mergulho na máquina", muscleGroup: "Tríceps", equipment: "Máquinas", instructions: "Ajuste o assento e empurre as alças para baixo sem elevar os ombros." },
  { name: "Prancha", muscleGroup: "Core", equipment: "Peso corporal", instructions: "Respire normalmente e mantenha o corpo alinhado pelo tempo confortável." },
  { name: "Leg press", muscleGroup: "Pernas", equipment: "Máquinas", instructions: "Ajuste o banco, mantenha os pés firmes e use amplitude confortável." },
  { name: "Leg press 45°", muscleGroup: "Pernas", equipment: "Máquinas", instructions: "Mantenha quadril e costas apoiados, pés firmes e joelhos alinhados durante o movimento." },
  { name: "Cadeira extensora", muscleGroup: "Pernas", equipment: "Máquinas", instructions: "Alinhe o joelho ao eixo da máquina e estenda as pernas sem lançar a carga." },
  { name: "Mesa flexora", muscleGroup: "Pernas", equipment: "Máquinas", instructions: "Ajuste o rolo acima dos calcanhares e flexione os joelhos mantendo o quadril apoiado." },
  { name: "Cadeira flexora", muscleGroup: "Pernas", equipment: "Máquinas", instructions: "Ajuste o encosto e flexione os joelhos com o tronco apoiado e movimento controlado." },
  { name: "Cadeira flexora unilateral", muscleGroup: "Pernas", equipment: "Máquinas", instructions: "Ajuste o encosto e flexione um joelho por vez mantendo o quadril apoiado." },
  { name: "Flexora em pé", muscleGroup: "Pernas", equipment: "Máquinas", instructions: "Apoie o tronco e flexione um joelho por vez sem movimentar o quadril." },
  { name: "Levantamento terra romeno", muscleGroup: "Pernas", equipment: "Barra ou halteres", instructions: "Leve o quadril para trás com a coluna neutra e mantenha a carga próxima às pernas." },
  { name: "Leg press horizontal", muscleGroup: "Pernas", equipment: "Máquinas", instructions: "Mantenha quadril e costas apoiados e empurre a plataforma sem travar os joelhos." },
  { name: "Agachamento búlgaro", muscleGroup: "Pernas", equipment: "Halteres", instructions: "Apoie o pé de trás no banco e desça de forma estável mantendo o joelho alinhado." },
  { name: "Passada no smith", muscleGroup: "Pernas", equipment: "Máquinas", instructions: "Posicione os pés em passada e desça verticalmente com estabilidade." },
  { name: "Cadeira extensora unilateral", muscleGroup: "Pernas", equipment: "Máquinas", instructions: "Alinhe o joelho ao eixo da máquina e estenda uma perna por vez sem lançar a carga." },
  { name: "Cadeira adutora", muscleGroup: "Pernas", equipment: "Máquinas", instructions: "Mantenha o quadril apoiado e aproxime as pernas de forma controlada." },
  { name: "Panturrilha em pé na máquina", muscleGroup: "Panturrilhas", equipment: "Máquinas", instructions: "Apoie a parte da frente dos pés, mantenha os joelhos estáveis e eleve os calcanhares com controle." },
  { name: "Panturrilha no leg press", muscleGroup: "Panturrilhas", equipment: "Máquinas", instructions: "Mantenha apenas a parte da frente dos pés na plataforma e movimente os tornozelos sem flexionar os joelhos." },
  { name: "Panturrilha sentada", muscleGroup: "Panturrilhas", equipment: "Máquinas", instructions: "Ajuste o apoio sobre as coxas e eleve os calcanhares usando uma amplitude confortável." },
  { name: "Panturrilha no smith", muscleGroup: "Panturrilhas", equipment: "Máquinas", instructions: "Apoie a parte da frente dos pés em uma base estável e eleve os calcanhares com controle." },
  { name: "Panturrilha unilateral em pé", muscleGroup: "Panturrilhas", equipment: "Halteres", instructions: "Apoie-se para manter o equilíbrio e eleve um calcanhar por vez de forma controlada." },
  { name: "Hack squat", muscleGroup: "Pernas", equipment: "Máquinas", instructions: "Apoie costas e ombros, mantenha os pés firmes e use uma amplitude confortável." },
  { name: "Agachamento no smith", muscleGroup: "Pernas", equipment: "Máquinas", instructions: "Posicione os pés de forma estável e desça com controle mantendo os joelhos alinhados." },
  { name: "Agachamento goblet", muscleGroup: "Pernas", equipment: "Halteres", instructions: "Segure o halter junto ao peito e controle a descida." },
  { name: "Abdução de quadril", muscleGroup: "Glúteos", equipment: "Faixas elásticas", instructions: "Mantenha o tronco estável e execute sem impulso." },
  { name: "Cadeira abdutora", muscleGroup: "Glúteos", equipment: "Máquinas", instructions: "Mantenha o quadril apoiado e abra as pernas de forma controlada." },
  { name: "Hip thrust na máquina", muscleGroup: "Glúteos", equipment: "Máquinas", instructions: "Ajuste o apoio sobre o quadril e eleve sem hiperestender a região lombar." },
  { name: "Glúteo no cabo", muscleGroup: "Glúteos", equipment: "Cabos", instructions: "Prenda a tornozeleira e estenda o quadril sem girar o tronco." },
  { name: "Glúteo na máquina", muscleGroup: "Glúteos", equipment: "Máquinas", instructions: "Ajuste os apoios e empurre com uma perna por vez mantendo o quadril estável." },
  { name: "Coice na máquina", muscleGroup: "Glúteos", equipment: "Máquinas", instructions: "Apoie o tronco e empurre a plataforma para trás sem arquear excessivamente a lombar." },
  { name: "Agachamento sumô", muscleGroup: "Glúteos", equipment: "Halteres", instructions: "Use uma base ampla, mantenha os joelhos alinhados e desça com o tronco estável." },
  { name: "Ponte unilateral", muscleGroup: "Glúteos", equipment: "Peso corporal", instructions: "Eleve o quadril com controle e sem desconforto lombar." },
  { name: "Crucifixo com halteres", muscleGroup: "Peito", equipment: "Halteres", instructions: "Use carga confortável e mantenha leve flexão dos cotovelos." },
  { name: "Remada unilateral", muscleGroup: "Costas", equipment: "Halteres", instructions: "Apoie o tronco e puxe o halter sem girar o corpo." },
  { name: "Remada com faixa", muscleGroup: "Costas", equipment: "Faixas elásticas", instructions: "Mantenha a faixa estável e aproxime as escápulas com controle." },
  { name: "Desenvolvimento com faixa", muscleGroup: "Ombros", equipment: "Faixas elásticas", instructions: "Pressione acima da cabeça dentro de uma amplitude confortável." },
  { name: "Elevação lateral com faixa", muscleGroup: "Ombros", equipment: "Faixas elásticas", instructions: "Controle a resistência durante a subida e a descida." },
  { name: "Rosca com faixa", muscleGroup: "Bíceps", equipment: "Faixas elásticas", instructions: "Mantenha os cotovelos próximos ao corpo." },
  { name: "Rosca alternada", muscleGroup: "Bíceps", equipment: "Halteres", instructions: "Alterne os braços sem projetar os cotovelos para a frente." },
  { name: "Rosca martelo", muscleGroup: "Bíceps", equipment: "Halteres", instructions: "Use pegada neutra e mantenha os punhos alinhados." },
  { name: "Tríceps francês", muscleGroup: "Tríceps", equipment: "Halteres", instructions: "Mantenha os cotovelos estáveis e use amplitude confortável." },
  { name: "Tríceps testa", muscleGroup: "Tríceps", equipment: "Barra ou halteres", instructions: "Flexione apenas os cotovelos e controle a aproximação da carga." },
  { name: "Mergulho no banco", muscleGroup: "Tríceps", equipment: "Peso corporal", instructions: "Mantenha os ombros estáveis e use uma amplitude confortável." },
  { name: "Rosca de punho", muscleGroup: "Antebraços", equipment: "Barra ou halteres", instructions: "Apoie os antebraços e movimente somente os punhos." },
  { name: "Rosca inversa", muscleGroup: "Antebraços", equipment: "Barra ou halteres", instructions: "Use pegada pronada e mantenha os cotovelos próximos ao corpo." },
  { name: "Caminhada do fazendeiro", muscleGroup: "Antebraços", equipment: "Halteres", instructions: "Caminhe com postura ereta, passos controlados e pegada firme." },
  { name: "Rosca Zottman", muscleGroup: "Antebraços", equipment: "Halteres", instructions: "Suba com as palmas para cima, gire os punhos no topo e desça com as palmas para baixo." },
  { name: "Extensão de punho", muscleGroup: "Antebraços", equipment: "Barra ou halteres", instructions: "Apoie os antebraços e estenda os punhos sem retirar os braços do apoio." },
  { name: "Remada curvada", muscleGroup: "Costas", equipment: "Barra ou halteres", instructions: "Incline o tronco com a coluna neutra e puxe a carga em direção ao abdômen." },
  { name: "Pullover com halter", muscleGroup: "Costas", equipment: "Halteres", instructions: "Leve o halter para trás com controle, sem arquear excessivamente a lombar." },
  { name: "Stiff com halteres", muscleGroup: "Pernas", equipment: "Halteres", instructions: "Leve o quadril para trás mantendo a coluna neutra e os joelhos levemente flexionados." },
  { name: "Crucifixo inverso", muscleGroup: "Ombros", equipment: "Halteres", instructions: "Abra os braços com controle sem elevar os ombros." },
  { name: "Dead bug", muscleGroup: "Core", equipment: "Peso corporal", instructions: "Movimente braços e pernas alternadamente mantendo o tronco estável." },
  { name: "Abdominal na máquina", muscleGroup: "Core", equipment: "Máquinas", instructions: "Ajuste os apoios e flexione o tronco de forma controlada, sem puxar com os braços." },
] as const;

export async function ensureExerciseCatalog() {
  const catalog = await db.exercise.findMany({
    orderBy: [{ muscleGroup: "asc" }, { name: "asc" }],
  });
  const byName = new Map(catalog.map((exercise) => [exercise.name, exercise]));
  const changed = EXERCISE_CATALOG.filter((exercise) => {
    const existing = byName.get(exercise.name);
    return !existing || existing.muscleGroup !== exercise.muscleGroup || existing.equipment !== exercise.equipment || existing.instructions !== exercise.instructions;
  });

  if (!changed.length) return catalog;

  await db.$transaction(
    changed.map((exercise) =>
      db.exercise.upsert({
        where: { name: exercise.name },
        create: exercise,
        update: {
          muscleGroup: exercise.muscleGroup,
          equipment: exercise.equipment,
          instructions: exercise.instructions,
        },
      }),
    ),
  );

  return db.exercise.findMany({
    orderBy: [{ muscleGroup: "asc" }, { name: "asc" }],
  });
}

export const STARTER_TEMPLATE = {
  name: "Corpo inteiro · 3 dias",
  days: [
    ["Agachamento livre", "Flexão de braços", "Remada sentada", "Panturrilha em pé na máquina"],
    ["Avanço alternado", "Supino reto", "Puxada frontal", "Elevação pélvica"],
    ["Agachamento livre", "Desenvolvimento de ombros", "Rosca direta", "Tríceps no cabo"],
  ],
} as const;
